# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plans.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plans.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bplans.proto\x12\x05plans\"\x11\n\x0fGetPlansRequest\"\xb4\x01\n\x0cPlanResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06module\x18\x02 \x01(\t\x12\x13\n\x0btrial_users\x18\x03 \x01(\x05\x12\x11\n\tmin_users\x18\x04 \x01(\x05\x12\x11\n\tmax_users\x18\x05 \x01(\x05\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x13\n\x0bis_per_user\x18\x07 \x01(\x08\x12\x16\n\x0eper_user_price\x18\x08 \x01(\x01\x12\x11\n\tis_active\x18\t \x01(\x08\"7\n\x11PlansListResponse\x12\"\n\x05plans\x18\x01 \x03(\x0b\x32\x13.plans.PlanResponse2P\n\x0cPlansService\x12@\n\x0cGetPlansList\x12\x16.plans.GetPlansRequest\x1a\x18.plans.PlansListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plans_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPLANSREQUEST']._serialized_start=22
  _globals['_GETPLANSREQUEST']._serialized_end=39
  _globals['_PLANRESPONSE']._serialized_start=42
  _globals['_PLANRESPONSE']._serialized_end=222
  _globals['_PLANSLISTRESPONSE']._serialized_start=224
  _globals['_PLANSLISTRESPONSE']._serialized_end=279
  _globals['_PLANSSERVICE']._serialized_start=281
  _globals['_PLANSSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
