# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plans.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plans.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bplans.proto\x12\x05plans\"/\n\x1aGetTenantActivePlanRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\x05\"\xf7\x01\n\x12\x41\x63tivePlanResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x12\n\nplan_price\x18\x04 \x01(\x01\x12\x13\n\x0busers_count\x18\x05 \x01(\x05\x12\x16\n\x0eper_user_price\x18\x06 \x01(\x01\x12\x0e\n\x06module\x18\x07 \x01(\t\x12\x13\n\x0bis_per_user\x18\x08 \x01(\x08\x12\x13\n\x0btrial_users\x18\t \x01(\x05\x12\x0c\n\x04plan\x18\n \x01(\x05\x12\x0e\n\x06tenant\x18\x0b \x01(\x05\x12\x1b\n\x13\x63urrent_users_count\x18\x0c \x01(\x05\"O\n\x1cGetTenantActivePlansResponse\x12/\n\x0c\x61\x63tive_plans\x18\x01 \x03(\x0b\x32\x19.plans.ActivePlanResponse2r\n\x11TenantPlanService\x12]\n\x13GetTenantActivePlan\x12!.plans.GetTenantActivePlanRequest\x1a#.plans.GetTenantActivePlansResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plans_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTENANTACTIVEPLANREQUEST']._serialized_start=22
  _globals['_GETTENANTACTIVEPLANREQUEST']._serialized_end=69
  _globals['_ACTIVEPLANRESPONSE']._serialized_start=72
  _globals['_ACTIVEPLANRESPONSE']._serialized_end=319
  _globals['_GETTENANTACTIVEPLANSRESPONSE']._serialized_start=321
  _globals['_GETTENANTACTIVEPLANSRESPONSE']._serialized_end=400
  _globals['_TENANTPLANSERVICE']._serialized_start=402
  _globals['_TENANTPLANSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
