# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tenant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tenant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctenant.proto\x12\x06tenant\"\x13\n\x11GetTenantsRequest\"?\n\x0eTenantResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bschema_name\x18\x03 \x01(\t\"=\n\x12GetTenantsResponse\x12\'\n\x07tenants\x18\x01 \x03(\x0b\x32\x16.tenant.TenantResponse2T\n\rTenantService\x12\x43\n\nGetTenants\x12\x19.tenant.GetTenantsRequest\x1a\x1a.tenant.GetTenantsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTENANTSREQUEST']._serialized_start=24
  _globals['_GETTENANTSREQUEST']._serialized_end=43
  _globals['_TENANTRESPONSE']._serialized_start=45
  _globals['_TENANTRESPONSE']._serialized_end=108
  _globals['_GETTENANTSRESPONSE']._serialized_start=110
  _globals['_GETTENANTSRESPONSE']._serialized_end=171
  _globals['_TENANTSERVICE']._serialized_start=173
  _globals['_TENANTSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
