syntax = "proto3";
package tenant;

service TenantService {
  rpc GetTenants (GetTenantsRequest) returns (GetTenantsResponse);
  rpc GetTenantsByIds (GetTenantsByIdsRequest) returns (GetTenantsResponse);
  rpc GetTenantById (GetTenantByIdRequest) returns (TenantResponse);
}

message GetTenantsRequest {}
message GetTenantsByIdsRequest {
  repeated int32 ids = 1;
}
message GetTenantByIdRequest {
  int32 id = 1;
}

message MonthlyTransResponse {
  int32 id = 1;
  string month = 2;
  double debt_amount = 3;
  double paid_amount = 4;
  string status = 5;
}

message TenantResponse {
  int32 id = 1;
  string name = 2;
  string schema_name = 3;
  string created_on = 4;
  string activated_at = 5;
  string deadline = 6;
  bool on_trial = 8;
  bool is_active = 9;
  bool is_deleted = 10;
  int32 empl_count = 11;
  int32 active_plan_amount = 12;
  repeated MonthlyTransResponse monthly_trans = 13;
}

message GetTenantsResponse {
  repeated TenantResponse tenants = 1;
}
