"""updated_seller_trans

Revision ID: 1370d17a0c4b
Revises: d4ac0f6687f0
Create Date: 2026-05-14 11:25:54.434307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1370d17a0c4b'
down_revision: Union[str, Sequence[str], None] = 'd4ac0f6687f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_transactions', sa.Column('month', sa.Date(), nullable=False, comment='Transaction Month'))
    op.alter_column('supervisors', 'from_date',
               existing_type=sa.DATE(),
               comment='The start date of the assistants deadline',
               existing_comment='The start date of the supervisor deadline',
               existing_nullable=False)
    op.alter_column('supervisors', 'to_date',
               existing_type=sa.DATE(),
               comment='The end date of the assistants deadline',
               existing_comment='The end date of the supervisor deadline',
               existing_nullable=False)
    op.alter_column('supervisors', 'percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='The percentage of the assistants deadline',
               existing_comment='The percentage of the supervisor deadline',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supervisors', 'percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='The percentage of the supervisor deadline',
               existing_comment='The percentage of the assistants deadline',
               existing_nullable=False)
    op.alter_column('supervisors', 'to_date',
               existing_type=sa.DATE(),
               comment='The end date of the supervisor deadline',
               existing_comment='The end date of the assistants deadline',
               existing_nullable=False)
    op.alter_column('supervisors', 'from_date',
               existing_type=sa.DATE(),
               comment='The start date of the supervisor deadline',
               existing_comment='The start date of the assistants deadline',
               existing_nullable=False)
    op.drop_column('seller_transactions', 'month')
    # ### end Alembic commands ###
