"""supervisors

Revision ID: 3f0ff8ecc352
Revises: 27c39958ee04
Create Date: 2026-05-09 16:24:22.001308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0ff8ecc352'
down_revision: Union[str, Sequence[str], None] = '27c39958ee04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisors',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False, comment='The start date of the supervisor deadline'),
    sa.Column('to_date', sa.Date(), nullable=False, comment='The end date of the supervisor deadline'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='The percentage of the supervisor deadline'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisors_id'), 'supervisors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisors_id'), table_name='supervisors')
    op.drop_table('supervisors')
    # ### end Alembic commands ###
