"""tenant_tg_message

Revision ID: 7490a8efa815
Revises: 75420468342c
Create Date: 2026-05-18 10:04:34.758486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7490a8efa815'
down_revision: Union[str, Sequence[str], None] = '75420468342c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_tg_chat',
    sa.Column('name', sa.String(), nullable=False, comment='Telegram chat name'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='Telegram chat id'),
    sa.Column('message_thread_id', sa.Integer(), server_default='0', nullable=False, comment='Super chats topic id'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is active?'),
    sa.Column('core_tenant_id', sa.Integer(), nullable=False, comment='Core service client id'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_tg_chat_id'), 'tenant_tg_chat', ['id'], unique=False)
    op.create_table('tg_chat_message_history',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=555), nullable=False, comment='Sent message body'),
    sa.Column('is_delivered', sa.Boolean(), nullable=False, comment='Is delivered?'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['tenant_tg_chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_chat_message_history_id'), 'tg_chat_message_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_chat_message_history_id'), table_name='tg_chat_message_history')
    op.drop_table('tg_chat_message_history')
    op.drop_index(op.f('ix_tenant_tg_chat_id'), table_name='tenant_tg_chat')
    op.drop_table('tenant_tg_chat')
    # ### end Alembic commands ###
