"""initial

Revision ID: 75420468342c
Revises: 
Create Date: 2026-05-16 11:13:48.141696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75420468342c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False, comment='Username'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(length=255), nullable=False, comment="User's password"),
    sa.Column('phone', sa.String(length=255), nullable=True, comment="User's phone number"),
    sa.Column('role', sa.Enum('admin', 'seller', 'super_admin', name='userroles'), server_default='seller', nullable=False, comment="User's role"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user is active'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment="User's percentage"),
    sa.Column('duration', sa.Integer(), nullable=False, comment='The duration of the user'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('seller_requests',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=2), server_default='0', nullable=False, comment='The amount of the seller request'),
    sa.Column('date', sa.Date(), nullable=False, comment='The date of the seller request'),
    sa.Column('condition', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='requestconditions'), nullable=False, comment='The condition of the seller request'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_requests_id'), 'seller_requests', ['id'], unique=False)
    op.create_table('supervisors',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False, comment='The start date of the assistants deadline'),
    sa.Column('to_date', sa.Date(), nullable=False, comment='The end date of the assistants deadline'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='The percentage of the assistants deadline'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisors_id'), 'supervisors', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('core_tenant_id', sa.Integer(), nullable=False, comment='Tenant id: in core service!'),
    sa.Column('type', sa.Enum('IMB_EDU', 'IMB_HR', name='tenanttypes'), nullable=False, comment='The type of the tenant'),
    sa.Column('from_date', sa.Date(), nullable=False, comment='The start date of the tenant'),
    sa.Column('to_date', sa.Date(), nullable=False, comment='The end date of the tenant'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='The percentage of the tenant'),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('tenant_monthly_transactions',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Core service, MonthlyTransaction ID'),
    sa.Column('month', sa.Date(), nullable=False, comment='Month: format YEAR-MONTH-01'),
    sa.Column('amount', sa.Numeric(precision=36, scale=2), server_default='0.00', nullable=False, comment='Month: amount of monthly transaction'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_monthly_transactions_id'), 'tenant_monthly_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_monthly_transactions_id'), table_name='tenant_monthly_transactions')
    op.drop_table('tenant_monthly_transactions')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_supervisors_id'), table_name='supervisors')
    op.drop_table('supervisors')
    op.drop_index(op.f('ix_seller_requests_id'), table_name='seller_requests')
    op.drop_table('seller_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
