"""tenant_tg_message_updated

Revision ID: 863752d78adb
Revises: 7490a8efa815
Create Date: 2026-05-18 10:09:42.321901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863752d78adb'
down_revision: Union[str, Sequence[str], None] = '7490a8efa815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_tg_chat', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Telegram chat id',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_tg_chat', 'chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Telegram chat id',
               existing_nullable=False)
    # ### end Alembic commands ###
