"""supervisors

Revision ID: d4ac0f6687f0
Revises: 3f0ff8ecc352
Create Date: 2026-05-09 16:31:25.762614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ac0f6687f0'
down_revision: Union[str, Sequence[str], None] = '3f0ff8ecc352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('seller_requests_seller_id_fkey'), 'seller_requests', type_='foreignkey')
    op.drop_column('seller_requests', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_requests', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('seller_requests_seller_id_fkey'), 'seller_requests', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
