"""tenant_seller_nullable

Revision ID: d5a2889de7d1
Revises: 863752d78adb
Create Date: 2026-05-18 11:30:19.812230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a2889de7d1'
down_revision: Union[str, Sequence[str], None] = '863752d78adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('tenants_seller_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_seller_id_fkey'), 'tenants', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenants', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
