"""message history

Revision ID: f9dccb8c6b28
Revises: d5a2889de7d1
Create Date: 2026-05-18 15:11:47.147417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dccb8c6b28'
down_revision: Union[str, Sequence[str], None] = 'd5a2889de7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_chat_message_history', sa.Column('tg_response', sa.JSON(), nullable=True, comment='Telegram API response payload'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_chat_message_history', 'tg_response')
    # ### end Alembic commands ###
