# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tenant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tenant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctenant.proto\x12\x06tenant\"\x13\n\x11GetTenantsRequest\"\xc9\x01\n\x0eTenantResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bschema_name\x18\x03 \x01(\t\x12\x12\n\ncreated_on\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63tivated_at\x18\x05 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x06 \x01(\t\x12\x13\n\x0bpermissions\x18\x07 \x03(\t\x12\x10\n\x08on_trial\x18\x08 \x01(\x08\x12\x11\n\tis_active\x18\t \x01(\x08\x12\x12\n\nis_deleted\x18\n \x01(\x08\"=\n\x12GetTenantsResponse\x12\'\n\x07tenants\x18\x01 \x03(\x0b\x32\x16.tenant.TenantResponse2T\n\rTenantService\x12\x43\n\nGetTenants\x12\x19.tenant.GetTenantsRequest\x1a\x1a.tenant.GetTenantsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTENANTSREQUEST']._serialized_start=24
  _globals['_GETTENANTSREQUEST']._serialized_end=43
  _globals['_TENANTRESPONSE']._serialized_start=46
  _globals['_TENANTRESPONSE']._serialized_end=247
  _globals['_GETTENANTSRESPONSE']._serialized_start=249
  _globals['_GETTENANTSRESPONSE']._serialized_end=310
  _globals['_TENANTSERVICE']._serialized_start=312
  _globals['_TENANTSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
