"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import salaries_pb2 as _salaries_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SalaryServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SalaryServiceAsyncStub: ...
    GetGroupedSalaries: _grpc.UnaryUnaryMultiCallable[_salaries_pb2.GroupedSalariesRequest, _salaries_pb2.GroupedSalaryListResponse]
    GetSalaryEmployees: _grpc.UnaryUnaryMultiCallable[_salaries_pb2.SalaryEmployeesRequest, _salaries_pb2.SalaryEmployeeListResponse]

@_typing.type_check_only
class SalaryServiceAsyncStub(SalaryServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetGroupedSalaries: _aio.UnaryUnaryMultiCallable[_salaries_pb2.GroupedSalariesRequest, _salaries_pb2.GroupedSalaryListResponse]  # type: ignore[assignment]
    GetSalaryEmployees: _aio.UnaryUnaryMultiCallable[_salaries_pb2.SalaryEmployeesRequest, _salaries_pb2.SalaryEmployeeListResponse]  # type: ignore[assignment]

class SalaryServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetGroupedSalaries(
        self,
        request: _salaries_pb2.GroupedSalariesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_salaries_pb2.GroupedSalaryListResponse, _abc.Awaitable[_salaries_pb2.GroupedSalaryListResponse]]: ...

    @_abc_1.abstractmethod
    def GetSalaryEmployees(
        self,
        request: _salaries_pb2.SalaryEmployeesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_salaries_pb2.SalaryEmployeeListResponse, _abc.Awaitable[_salaries_pb2.SalaryEmployeeListResponse]]: ...

def add_SalaryServiceServicer_to_server(servicer: SalaryServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
