"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GroupedSalariesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GroupedSalariesRequest: _TypeAlias = GroupedSalariesRequest  # noqa: Y015

@_typing.final
class SalaryEmployeesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SALARY_ID_FIELD_NUMBER: _builtins.int
    salary_id: _builtins.int
    def __init__(
        self,
        *,
        salary_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["salary_id", b"salary_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SalaryEmployeesRequest: _TypeAlias = SalaryEmployeesRequest  # noqa: Y015

@_typing.final
class GroupedSalaryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FROM_DATE_FIELD_NUMBER: _builtins.int
    TO_DATE_FIELD_NUMBER: _builtins.int
    EMPL_COUNT_FIELD_NUMBER: _builtins.int
    IS_APPROVED_FIELD_NUMBER: _builtins.int
    SALARIES_AMOUNT_FIELD_NUMBER: _builtins.int
    GROUP_ID_FIELD_NUMBER: _builtins.int
    ADVANCES_FIELD_NUMBER: _builtins.int
    BONUSES_FIELD_NUMBER: _builtins.int
    FINES_FIELD_NUMBER: _builtins.int
    FINAL_SALARY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    name: _builtins.str
    from_date: _builtins.str
    to_date: _builtins.str
    empl_count: _builtins.int
    is_approved: _builtins.bool
    salaries_amount: _builtins.float
    group_id: _builtins.int
    advances: _builtins.float
    bonuses: _builtins.float
    fines: _builtins.float
    final_salary: _builtins.float
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        name: _builtins.str = ...,
        from_date: _builtins.str = ...,
        to_date: _builtins.str = ...,
        empl_count: _builtins.int = ...,
        is_approved: _builtins.bool = ...,
        salaries_amount: _builtins.float = ...,
        group_id: _builtins.int = ...,
        advances: _builtins.float = ...,
        bonuses: _builtins.float = ...,
        fines: _builtins.float = ...,
        final_salary: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["advances", b"advances", "bonuses", b"bonuses", "empl_count", b"empl_count", "final_salary", b"final_salary", "fines", b"fines", "from_date", b"from_date", "group_id", b"group_id", "id", b"id", "is_approved", b"is_approved", "name", b"name", "salaries_amount", b"salaries_amount", "to_date", b"to_date"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GroupedSalaryResponse: _TypeAlias = GroupedSalaryResponse  # noqa: Y015

@_typing.final
class GroupedSalaryListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___GroupedSalaryResponse]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___GroupedSalaryResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GroupedSalaryListResponse: _TypeAlias = GroupedSalaryListResponse  # noqa: Y015

@_typing.final
class SalaryEmployeeItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EMPLOYEE_ID_FIELD_NUMBER: _builtins.int
    FULL_NAME_FIELD_NUMBER: _builtins.int
    SALARY_FIELD_NUMBER: _builtins.int
    ADVANCES_FIELD_NUMBER: _builtins.int
    BONUSES_FIELD_NUMBER: _builtins.int
    FINES_FIELD_NUMBER: _builtins.int
    FINAL_SALARY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    employee_id: _builtins.int
    full_name: _builtins.str
    salary: _builtins.float
    advances: _builtins.float
    bonuses: _builtins.float
    fines: _builtins.float
    final_salary: _builtins.float
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        employee_id: _builtins.int = ...,
        full_name: _builtins.str = ...,
        salary: _builtins.float = ...,
        advances: _builtins.float = ...,
        bonuses: _builtins.float = ...,
        fines: _builtins.float = ...,
        final_salary: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["advances", b"advances", "bonuses", b"bonuses", "employee_id", b"employee_id", "final_salary", b"final_salary", "fines", b"fines", "full_name", b"full_name", "id", b"id", "salary", b"salary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SalaryEmployeeItem: _TypeAlias = SalaryEmployeeItem  # noqa: Y015

@_typing.final
class SalaryEmployeeListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___SalaryEmployeeItem]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___SalaryEmployeeItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SalaryEmployeeListResponse: _TypeAlias = SalaryEmployeeListResponse  # noqa: Y015
