"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import plans_pb2 as _plans_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PlansServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PlansServiceAsyncStub: ...
    GetPlansList: _grpc.UnaryUnaryMultiCallable[_plans_pb2.GetPlansRequest, _plans_pb2.PlansListResponse]

@_typing.type_check_only
class PlansServiceAsyncStub(PlansServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetPlansList: _aio.UnaryUnaryMultiCallable[_plans_pb2.GetPlansRequest, _plans_pb2.PlansListResponse]  # type: ignore[assignment]

class PlansServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetPlansList(
        self,
        request: _plans_pb2.GetPlansRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_plans_pb2.PlansListResponse, _abc.Awaitable[_plans_pb2.PlansListResponse]]: ...

def add_PlansServiceServicer_to_server(servicer: PlansServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
