"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetPlansRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPlansRequest: _TypeAlias = GetPlansRequest  # noqa: Y015

@_typing.final
class PlanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MODULE_FIELD_NUMBER: _builtins.int
    TRIAL_USERS_FIELD_NUMBER: _builtins.int
    MIN_USERS_FIELD_NUMBER: _builtins.int
    MAX_USERS_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    IS_PER_USER_FIELD_NUMBER: _builtins.int
    PER_USER_PRICE_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    module: _builtins.str
    trial_users: _builtins.int
    min_users: _builtins.int
    max_users: _builtins.int
    price: _builtins.float
    is_per_user: _builtins.bool
    per_user_price: _builtins.float
    is_active: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        module: _builtins.str = ...,
        trial_users: _builtins.int = ...,
        min_users: _builtins.int = ...,
        max_users: _builtins.int = ...,
        price: _builtins.float = ...,
        is_per_user: _builtins.bool = ...,
        per_user_price: _builtins.float = ...,
        is_active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_active", b"is_active", "is_per_user", b"is_per_user", "max_users", b"max_users", "min_users", b"min_users", "module", b"module", "per_user_price", b"per_user_price", "price", b"price", "trial_users", b"trial_users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlanResponse: _TypeAlias = PlanResponse  # noqa: Y015

@_typing.final
class PlansListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLANS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___PlanResponse]: ...
    def __init__(
        self,
        *,
        plans: _abc.Iterable[Global___PlanResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["plans", b"plans"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlansListResponse: _TypeAlias = PlansListResponse  # noqa: Y015
