"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetTenantsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsRequest: _TypeAlias = GetTenantsRequest  # noqa: Y015

@_typing.final
class GetTenantsByIdsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsByIdsRequest: _TypeAlias = GetTenantsByIdsRequest  # noqa: Y015

@_typing.final
class GetTenantByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantByIdRequest: _TypeAlias = GetTenantByIdRequest  # noqa: Y015

@_typing.final
class GetTenantsBalanceStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsBalanceStatusRequest: _TypeAlias = GetTenantsBalanceStatusRequest  # noqa: Y015

@_typing.final
class MonthlyTransResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    DEBT_AMOUNT_FIELD_NUMBER: _builtins.int
    PAID_AMOUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    month: _builtins.str
    debt_amount: _builtins.float
    paid_amount: _builtins.float
    status: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        month: _builtins.str = ...,
        debt_amount: _builtins.float = ...,
        paid_amount: _builtins.float = ...,
        status: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["debt_amount", b"debt_amount", "id", b"id", "month", b"month", "paid_amount", b"paid_amount", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MonthlyTransResponse: _TypeAlias = MonthlyTransResponse  # noqa: Y015

@_typing.final
class TenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SCHEMA_NAME_FIELD_NUMBER: _builtins.int
    CREATED_ON_FIELD_NUMBER: _builtins.int
    ACTIVATED_AT_FIELD_NUMBER: _builtins.int
    DEADLINE_FIELD_NUMBER: _builtins.int
    ON_TRIAL_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    IS_DELETED_FIELD_NUMBER: _builtins.int
    EMPL_COUNT_FIELD_NUMBER: _builtins.int
    ACTIVE_PLAN_AMOUNT_FIELD_NUMBER: _builtins.int
    MONTHLY_TRANS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    name: _builtins.str
    schema_name: _builtins.str
    created_on: _builtins.str
    activated_at: _builtins.str
    deadline: _builtins.str
    on_trial: _builtins.bool
    is_active: _builtins.bool
    is_deleted: _builtins.bool
    empl_count: _builtins.int
    active_plan_amount: _builtins.int
    @_builtins.property
    def monthly_trans(self) -> _containers.RepeatedCompositeFieldContainer[Global___MonthlyTransResponse]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        name: _builtins.str = ...,
        schema_name: _builtins.str = ...,
        created_on: _builtins.str = ...,
        activated_at: _builtins.str = ...,
        deadline: _builtins.str = ...,
        on_trial: _builtins.bool = ...,
        is_active: _builtins.bool = ...,
        is_deleted: _builtins.bool = ...,
        empl_count: _builtins.int = ...,
        active_plan_amount: _builtins.int = ...,
        monthly_trans: _abc.Iterable[Global___MonthlyTransResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activated_at", b"activated_at", "active_plan_amount", b"active_plan_amount", "created_on", b"created_on", "deadline", b"deadline", "empl_count", b"empl_count", "id", b"id", "is_active", b"is_active", "is_deleted", b"is_deleted", "monthly_trans", b"monthly_trans", "name", b"name", "on_trial", b"on_trial", "schema_name", b"schema_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TenantResponse: _TypeAlias = TenantResponse  # noqa: Y015

@_typing.final
class GetTenantsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tenants(self) -> _containers.RepeatedCompositeFieldContainer[Global___TenantResponse]: ...
    def __init__(
        self,
        *,
        tenants: _abc.Iterable[Global___TenantResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenants", b"tenants"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsResponse: _TypeAlias = GetTenantsResponse  # noqa: Y015

@_typing.final
class TenantsBalanceStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MUST_PAID_AMOUNT_FIELD_NUMBER: _builtins.int
    NOT_PAID_AMOUNT_FIELD_NUMBER: _builtins.int
    PAID_AMOUNT_FIELD_NUMBER: _builtins.int
    must_paid_amount: _builtins.float
    not_paid_amount: _builtins.float
    paid_amount: _builtins.float
    def __init__(
        self,
        *,
        must_paid_amount: _builtins.float = ...,
        not_paid_amount: _builtins.float = ...,
        paid_amount: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["must_paid_amount", b"must_paid_amount", "not_paid_amount", b"not_paid_amount", "paid_amount", b"paid_amount"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TenantsBalanceStatusResponse: _TypeAlias = TenantsBalanceStatusResponse  # noqa: Y015
