"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import tenant_pb2 as _tenant_pb2
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TenantServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TenantServiceAsyncStub: ...
    GetTenants: _grpc.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsRequest, _tenant_pb2.GetTenantsResponse]
    GetTenantsByIds: _grpc.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsByIdsRequest, _tenant_pb2.GetTenantsResponse]
    GetTenantById: _grpc.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantByIdRequest, _tenant_pb2.TenantResponse]
    GetTenantsBalanceStatus: _grpc.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsBalanceStatusRequest, _tenant_pb2.TenantsBalanceStatusResponse]

@_typing.type_check_only
class TenantServiceAsyncStub(TenantServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetTenants: _aio.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsRequest, _tenant_pb2.GetTenantsResponse]  # type: ignore[assignment]
    GetTenantsByIds: _aio.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsByIdsRequest, _tenant_pb2.GetTenantsResponse]  # type: ignore[assignment]
    GetTenantById: _aio.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantByIdRequest, _tenant_pb2.TenantResponse]  # type: ignore[assignment]
    GetTenantsBalanceStatus: _aio.UnaryUnaryMultiCallable[_tenant_pb2.GetTenantsBalanceStatusRequest, _tenant_pb2.TenantsBalanceStatusResponse]  # type: ignore[assignment]

class TenantServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetTenants(
        self,
        request: _tenant_pb2.GetTenantsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_tenant_pb2.GetTenantsResponse, _abc.Awaitable[_tenant_pb2.GetTenantsResponse]]: ...

    @_abc_1.abstractmethod
    def GetTenantsByIds(
        self,
        request: _tenant_pb2.GetTenantsByIdsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_tenant_pb2.GetTenantsResponse, _abc.Awaitable[_tenant_pb2.GetTenantsResponse]]: ...

    @_abc_1.abstractmethod
    def GetTenantById(
        self,
        request: _tenant_pb2.GetTenantByIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_tenant_pb2.TenantResponse, _abc.Awaitable[_tenant_pb2.TenantResponse]]: ...

    @_abc_1.abstractmethod
    def GetTenantsBalanceStatus(
        self,
        request: _tenant_pb2.GetTenantsBalanceStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_tenant_pb2.TenantsBalanceStatusResponse, _abc.Awaitable[_tenant_pb2.TenantsBalanceStatusResponse]]: ...

def add_TenantServiceServicer_to_server(servicer: TenantServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
