"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetTenantsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsRequest: _TypeAlias = GetTenantsRequest  # noqa: Y015

@_typing.final
class GetTenantsByIdsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsByIdsRequest: _TypeAlias = GetTenantsByIdsRequest  # noqa: Y015

@_typing.final
class GetTenantByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantByIdRequest: _TypeAlias = GetTenantByIdRequest  # noqa: Y015

@_typing.final
class TenantPlansResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PLAN_PRICE_FIELD_NUMBER: _builtins.int
    USERS_COUNT_FIELD_NUMBER: _builtins.int
    PER_USER_PRICE_FIELD_NUMBER: _builtins.int
    MODULE_FIELD_NUMBER: _builtins.int
    CURRENT_USERS_COUNT_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    plan_price: _builtins.float
    users_count: _builtins.int
    per_user_price: _builtins.float
    module: _builtins.str
    current_users_count: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        plan_price: _builtins.float = ...,
        users_count: _builtins.int = ...,
        per_user_price: _builtins.float = ...,
        module: _builtins.str = ...,
        current_users_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_users_count", b"current_users_count", "id", b"id", "module", b"module", "per_user_price", b"per_user_price", "plan_price", b"plan_price", "users_count", b"users_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TenantPlansResponse: _TypeAlias = TenantPlansResponse  # noqa: Y015

@_typing.final
class TenantResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SCHEMA_NAME_FIELD_NUMBER: _builtins.int
    CREATED_ON_FIELD_NUMBER: _builtins.int
    ACTIVATED_AT_FIELD_NUMBER: _builtins.int
    DEADLINE_FIELD_NUMBER: _builtins.int
    PERMISSIONS_FIELD_NUMBER: _builtins.int
    ON_TRIAL_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    IS_DELETED_FIELD_NUMBER: _builtins.int
    PLANS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    name: _builtins.str
    schema_name: _builtins.str
    created_on: _builtins.str
    activated_at: _builtins.str
    deadline: _builtins.str
    on_trial: _builtins.bool
    is_active: _builtins.bool
    is_deleted: _builtins.bool
    @_builtins.property
    def permissions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___TenantPlansResponse]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        name: _builtins.str = ...,
        schema_name: _builtins.str = ...,
        created_on: _builtins.str = ...,
        activated_at: _builtins.str = ...,
        deadline: _builtins.str = ...,
        permissions: _abc.Iterable[_builtins.str] | None = ...,
        on_trial: _builtins.bool = ...,
        is_active: _builtins.bool = ...,
        is_deleted: _builtins.bool = ...,
        plans: _abc.Iterable[Global___TenantPlansResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activated_at", b"activated_at", "created_on", b"created_on", "deadline", b"deadline", "id", b"id", "is_active", b"is_active", "is_deleted", b"is_deleted", "name", b"name", "on_trial", b"on_trial", "permissions", b"permissions", "plans", b"plans", "schema_name", b"schema_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TenantResponse: _TypeAlias = TenantResponse  # noqa: Y015

@_typing.final
class GetTenantsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tenants(self) -> _containers.RepeatedCompositeFieldContainer[Global___TenantResponse]: ...
    def __init__(
        self,
        *,
        tenants: _abc.Iterable[Global___TenantResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenants", b"tenants"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantsResponse: _TypeAlias = GetTenantsResponse  # noqa: Y015
