"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetTenantActivePlanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: _builtins.int
    tenant_id: _builtins.int
    def __init__(
        self,
        *,
        tenant_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantActivePlanRequest: _TypeAlias = GetTenantActivePlanRequest  # noqa: Y015

@_typing.final
class ActivePlanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DATE_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    PLAN_PRICE_FIELD_NUMBER: _builtins.int
    USERS_COUNT_FIELD_NUMBER: _builtins.int
    PER_USER_PRICE_FIELD_NUMBER: _builtins.int
    MODULE_FIELD_NUMBER: _builtins.int
    IS_PER_USER_FIELD_NUMBER: _builtins.int
    TRIAL_USERS_FIELD_NUMBER: _builtins.int
    PLAN_FIELD_NUMBER: _builtins.int
    TENANT_FIELD_NUMBER: _builtins.int
    CURRENT_USERS_COUNT_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    date: _builtins.str
    is_active: _builtins.bool
    plan_price: _builtins.float
    users_count: _builtins.int
    per_user_price: _builtins.float
    module: _builtins.str
    is_per_user: _builtins.bool
    trial_users: _builtins.int
    plan: _builtins.int
    tenant: _builtins.int
    current_users_count: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        date: _builtins.str = ...,
        is_active: _builtins.bool = ...,
        plan_price: _builtins.float = ...,
        users_count: _builtins.int = ...,
        per_user_price: _builtins.float = ...,
        module: _builtins.str = ...,
        is_per_user: _builtins.bool = ...,
        trial_users: _builtins.int = ...,
        plan: _builtins.int = ...,
        tenant: _builtins.int = ...,
        current_users_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_users_count", b"current_users_count", "date", b"date", "id", b"id", "is_active", b"is_active", "is_per_user", b"is_per_user", "module", b"module", "per_user_price", b"per_user_price", "plan", b"plan", "plan_price", b"plan_price", "tenant", b"tenant", "trial_users", b"trial_users", "users_count", b"users_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivePlanResponse: _TypeAlias = ActivePlanResponse  # noqa: Y015

@_typing.final
class GetTenantActivePlansResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACTIVE_PLANS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def active_plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActivePlanResponse]: ...
    def __init__(
        self,
        *,
        active_plans: _abc.Iterable[Global___ActivePlanResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_plans", b"active_plans"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTenantActivePlansResponse: _TypeAlias = GetTenantActivePlansResponse  # noqa: Y015
